import { useState } from 'react'
import { FaTrash, FaCalendarAlt, FaTag, FaPrint, FaFileAlt, FaEdit } from 'react-icons/fa'
import ConfirmationModal from './ConfirmationModal'
import EditExpenseModal from './EditExpenseModal'
import useExpenseStore from '../stores/expenseStore'

const ExpenseList = () => {
  const expenses = useExpenseStore((state) => state.expenses)
  const removeExpense = useExpenseStore((state) => state.removeExpense)
  const updateExpense = useExpenseStore((state) => state.updateExpense)
  
  const [showPrintModal, setShowPrintModal] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [selectedExpense, setSelectedExpense] = useState(null)
  const [expenseToDelete, setExpenseToDelete] = useState(null)
  
  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-NG', {
      day: 'numeric',
      month: 'short',
      year: 'numeric'
    })
  }
  
  const formatAmount = (amount) => {
    return new Intl.NumberFormat('en-NG', {
      style: 'currency',
      currency: 'NGN',
      minimumFractionDigits: 2
    }).format(amount)
  }

  const handlePrint = () => {
    // Create a new window for printing
    const printWindow = window.open('', '_blank', 'width=800,height=600')
    
    // Get current date and time
    const now = new Date()
    const generatedDate = now.toLocaleDateString('en-NG', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
    
    // Calculate total
    const totalSpent = expenses.reduce((total, expense) => total + expense.amount, 0)
    
    // Create HTML content
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Expense Report - Naija Expense Tracker</title>
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 40px;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 3px solid #008751;
            padding-bottom: 25px;
          }
          .header h1 {
            color: #008751;
            margin: 0 0 10px 0;
            font-size: 28px;
          }
          .meta {
            color: #666;
            font-size: 14px;
            margin-top: 10px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 30px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          }
          th {
            background-color: #f8f9fa;
            text-align: left;
            padding: 15px;
            border: 1px solid #dee2e6;
            font-weight: 600;
            color: #333;
          }
          td {
            padding: 15px;
            border: 1px solid #dee2e6;
          }
          tr:nth-child(even) {
            background-color: #f9f9f9;
          }
          .total-row {
            background-color: #f8f9fa;
            font-weight: bold;
            font-size: 16px;
          }
          .footer {
            margin-top: 50px;
            text-align: center;
            color: #666;
            font-size: 12px;
            border-top: 1px solid #dee2e6;
            padding-top: 20px;
          }
          @media print {
            body {
              margin: 20px;
            }
            .no-print {
              display: none;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Expense Report</h1>
          <div class="meta">
            <strong>Generated on:</strong> ${generatedDate}<br>
            <strong>Total Expenses:</strong> ${expenses.length}
          </div>
        </div>
        
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Description</th>
              <th>Category</th>
              <th>Amount (₦)</th>
            </tr>
          </thead>
          <tbody>
            ${expenses.map(expense => `
              <tr>
                <td>${formatDate(expense.date)}</td>
                <td>${expense.description}</td>
                <td>${expense.category}</td>
                <td>${formatAmount(expense.amount)}</td>
              </tr>
            `).join('')}
            <tr class="total-row">
              <td colspan="3"><strong>Total Spent</strong></td>
              <td><strong>${formatAmount(totalSpent)}</strong></td>
            </tr>
          </tbody>
        </table>
        
        <div class="footer">
          <p>Generated by Naija Expense Tracker</p>
          <p>For personal financial management</p>
        </div>
        
        <div class="no-print" style="margin-top: 30px; text-align: center;">
          <button onclick="window.print()" style="
            background: #008751;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 6px;
            cursor: pointer;
            font-size: 16px;
            margin-right: 10px;
          ">Print Report</button>
          <button onclick="window.close()" style="
            background: #6c757d;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 6px;
            cursor: pointer;
            font-size: 16px;
          ">Close Window</button>
        </div>
      </body>
      </html>
    `
    
    // Write content and open print dialog
    printWindow.document.write(htmlContent)
    printWindow.document.close()
    
    // Focus on the new window
    printWindow.focus()
    
    // Close the modal
    setShowPrintModal(false)
  }

  const handleDelete = () => {
    if (expenseToDelete) {
      removeExpense(expenseToDelete)
      setShowDeleteModal(false)
      setExpenseToDelete(null)
    }
  }

  const handleEdit = (expense) => {
    setSelectedExpense(expense)
    setShowEditModal(true)
  }

  const handleSaveEdit = (updatedExpense) => {
    if (selectedExpense && updatedExpense) {
      updateExpense(selectedExpense.id, {
        description: updatedExpense.description,
        amount: updatedExpense.amount,
        category: updatedExpense.category,
        date: updatedExpense.date
      })
      setShowEditModal(false)
      setSelectedExpense(null)
    }
  }

  const totalSpent = expenses.reduce((total, expense) => total + expense.amount, 0)
  
  if (expenses.length === 0) {
    return (
      <div className="bg-white rounded-xl shadow-lg p-8 text-center">
        <div className="text-gray-400 mb-4">
          <FaFileAlt className="w-16 h-16 mx-auto" />
        </div>
        <h3 className="text-xl font-semibold text-gray-600 mb-2">No expenses yet</h3>
        <p className="text-gray-500">Start by adding your first expense above!</p>
      </div>
    )
  }
  
  return (
    <>
      {/* Regular view */}
      <div className="bg-white rounded-xl shadow-lg p-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-6 space-y-3 sm:space-y-0">
          <h2 className="text-2xl font-bold text-naija-green">Expense History</h2>
          
          <div className="flex items-center space-x-3">
            <span className="text-sm text-gray-500 bg-gray-100 px-3 py-1 rounded-full">
              {expenses.length} expense{expenses.length !== 1 ? 's' : ''}
            </span>
            
            <button
              onClick={() => setShowPrintModal(true)}
              className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition duration-300"
            >
              <FaPrint className="mr-2" />
              Print Report
            </button>
          </div>
        </div>
        
        <div className="space-y-4">
          {expenses.map((expense, index) => (
            <div 
              key={expense.id} 
              className="animate-slide-in"
              style={{ animationDelay: `${index * 0.05}s` }}
            >
              <div className="flex items-center justify-between p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition duration-200">
                <div className="flex items-center space-x-4">
                  <div className="w-10 h-10 flex items-center justify-center rounded-full bg-green-100 text-naija-green">
                    {expense.category.charAt(0)}
                  </div>
                  <div>
                    <h3 className="font-medium text-gray-900">{expense.description}</h3>
                    <div className="flex flex-wrap items-center gap-2 text-sm text-gray-500 mt-1">
                      <span className="px-2 py-1 bg-gray-100 rounded-full text-xs flex items-center">
                        <FaTag className="mr-1" size={10} />
                        {expense.category}
                      </span>
                      <span className="flex items-center">
                        <FaCalendarAlt className="mr-1" size={12} />
                        {formatDate(expense.date)}
                      </span>
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center space-x-3">
                  <span className="text-lg font-bold text-gray-900">
                    {formatAmount(expense.amount)}
                  </span>
                  <div className="flex items-center space-x-2">
                    <button
                      onClick={() => handleEdit(expense)}
                      className="p-2 text-blue-500 hover:text-blue-700 hover:bg-blue-50 rounded-lg transition duration-200"
                      title="Edit expense"
                    >
                      <FaEdit />
                    </button>
                    <button
                      onClick={() => {
                        setExpenseToDelete(expense.id)
                        setShowDeleteModal(true)
                      }}
                      className="p-2 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-lg transition duration-200"
                      title="Delete expense"
                    >
                      <FaTrash />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Print Confirmation Modal */}
      <ConfirmationModal
        isOpen={showPrintModal}
        onClose={() => setShowPrintModal(false)}
        onConfirm={handlePrint}
        title="Print Expense Report"
        message="A new window will open with a preview of your expense report. You can print or save it from there."
        confirmText="Generate Report"
        confirmColor="blue"
        icon={FaPrint}
      />

      {/* Delete Confirmation Modal */}
      <ConfirmationModal
        isOpen={showDeleteModal}
        onClose={() => {
          setShowDeleteModal(false)
          setExpenseToDelete(null)
        }}
        onConfirm={handleDelete}
        title="Delete Expense"
        message="Are you sure you want to delete this expense? This action cannot be undone."
        confirmText="Delete Expense"
        confirmColor="red"
        icon={FaTrash}
      />

      {/* Edit Expense Modal */}
      {showEditModal && selectedExpense && (
        <EditExpenseModal
          isOpen={showEditModal}
          onClose={() => {
            setShowEditModal(false)
            setSelectedExpense(null)
          }}
          onSave={handleSaveEdit}
          expense={selectedExpense}
        />
      )}
    </>
  )
}

export default ExpenseList