import { useState } from 'react'
import { FaTrash, FaCalendarAlt, FaTag, FaPrint, FaFileAlt, FaEdit } from 'react-icons/fa'
import { useSelector, useDispatch } from 'react-redux'
import ConfirmationModal from '../../ui/ConfirmationModal'
import EditExpenseModal from '../../ui/EditExpenseModal'
import { removeExpense, updateExpense, selectAllExpenses } from '../expenseSlice'

const ExpenseList = () => {
  const expenses = useSelector(selectAllExpenses)
  const dispatch = useDispatch()
  
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [showPrintModal, setShowPrintModal] = useState(false)
  const [selectedExpense, setSelectedExpense] = useState(null)
  const [expenseToDelete, setExpenseToDelete] = useState(null)
  
  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-NG', {
      day: 'numeric',
      month: 'short',
      year: 'numeric'
    })
  }
  
  const formatAmount = (amount) => {
    return new Intl.NumberFormat('en-NG', {
      style: 'currency',
      currency: 'NGN',
      minimumFractionDigits: 2
    }).format(amount)
  }

  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Expense Report - Redux Tracker</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; }
          .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #008751; padding-bottom: 20px; }
          .header h1 { color: #008751; margin: 0; }
          .meta { color: #666; font-size: 14px; margin-top: 10px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { background-color: #f8f9fa; text-align: left; padding: 12px; border: 1px solid #dee2e6; }
          td { padding: 12px; border: 1px solid #dee2e6; }
          .total-row { background-color: #f8f9fa; font-weight: bold; }
          .footer { margin-top: 40px; text-align: center; color: #666; font-size: 12px; border-top: 1px solid #dee2e6; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Expense Report (Redux Version)</h1>
          <div class="meta">
            Generated: ${new Date().toLocaleDateString('en-NG')}
          </div>
        </div>
        
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Description</th>
              <th>Category</th>
              <th>Amount (₦)</th>
            </tr>
          </thead>
          <tbody>
            ${expenses.map(expense => `
              <tr>
                <td>${formatDate(expense.date)}</td>
                <td>${expense.description}</td>
                <td>${expense.category}</td>
                <td>${formatAmount(expense.amount)}</td>
              </tr>
            `).join('')}
            <tr class="total-row">
              <td colspan="3">Total Spent</td>
              <td>${formatAmount(expenses.reduce((total, expense) => total + expense.amount, 0))}</td>
            </tr>
          </tbody>
        </table>
        
        <div class="footer">
          <p>Generated by Redux Expense Tracker</p>
          <p>Total Expenses: ${expenses.length}</p>
        </div>
        
        <script>
          window.onload = function() {
            window.print();
          }
        </script>
      </body>
      </html>
    `
    
    printWindow.document.write(htmlContent)
    printWindow.document.close()
    setShowPrintModal(false)
  }

  const handleDelete = () => {
    if (expenseToDelete) {
      dispatch(removeExpense(expenseToDelete))
      setShowDeleteModal(false)
      setExpenseToDelete(null)
    }
  }

  const handleEdit = (expense) => {
    setSelectedExpense(expense)
    setShowEditModal(true)
  }

  const handleSaveEdit = (updatedExpense) => {
    if (selectedExpense && updatedExpense) {
      dispatch(updateExpense({
        id: selectedExpense.id,
        updates: {
          description: updatedExpense.description,
          amount: updatedExpense.amount,
          category: updatedExpense.category,
          date: updatedExpense.date
        }
      }))
      setShowEditModal(false)
      setSelectedExpense(null)
    }
  }

  if (expenses.length === 0) {
    return (
      <div className="bg-white rounded-xl shadow-lg p-8 text-center">
        <div className="text-gray-400 mb-4">
          <FaFileAlt className="w-16 h-16 mx-auto" />
        </div>
        <h3 className="text-xl font-semibold text-gray-600 mb-2">No expenses yet</h3>
        <p className="text-gray-500">Start by adding your first expense above!</p>
      </div>
    )
  }
  
  return (
    <>
      <div className="bg-white rounded-xl shadow-lg p-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-6 space-y-3 sm:space-y-0">
          <h2 className="text-2xl font-bold text-naija-green">Expense History</h2>
          
          <div className="flex items-center space-x-3">
            <span className="text-sm text-gray-500 bg-gray-100 px-3 py-1 rounded-full">
              {expenses.length} expense{expenses.length !== 1 ? 's' : ''}
            </span>
            
            <button
              onClick={() => setShowPrintModal(true)}
              className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition duration-300"
            >
              <FaPrint className="mr-2" />
              Print Report
            </button>
          </div>
        </div>
        
        <div className="space-y-4">
          {expenses.map((expense, index) => (
            <div key={expense.id} className="animate-slide-in">
              <div className="flex items-center justify-between p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition duration-200">
                <div className="flex items-center space-x-4">
                  <div className="w-10 h-10 flex items-center justify-center rounded-full bg-green-100 text-naija-green">
                    {expense.category.charAt(0)}
                  </div>
                  <div>
                    <h3 className="font-medium text-gray-900">{expense.description}</h3>
                    <div className="flex flex-wrap items-center gap-2 text-sm text-gray-500 mt-1">
                      <span className="px-2 py-1 bg-gray-100 rounded-full text-xs flex items-center">
                        <FaTag className="mr-1" size={10} />
                        {expense.category}
                      </span>
                      <span className="flex items-center">
                        <FaCalendarAlt className="mr-1" size={12} />
                        {formatDate(expense.date)}
                      </span>
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center space-x-3">
                  <span className="text-lg font-bold text-gray-900">
                    {formatAmount(expense.amount)}
                  </span>
                  <div className="flex items-center space-x-2">
                    <button
                      onClick={() => handleEdit(expense)}
                      className="p-2 text-blue-500 hover:text-blue-700 hover:bg-blue-50 rounded-lg transition duration-200"
                      title="Edit expense"
                    >
                      <FaEdit />
                    </button>
                    <button
                      onClick={() => {
                        setExpenseToDelete(expense.id)
                        setShowDeleteModal(true)
                      }}
                      className="p-2 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-lg transition duration-200"
                      title="Delete expense"
                    >
                      <FaTrash />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <ConfirmationModal
        isOpen={showPrintModal}
        onClose={() => setShowPrintModal(false)}
        onConfirm={handlePrint}
        title="Print Expense Report"
        message="A new window will open with a preview of your expense report. You can print or save it from there."
        confirmText="Generate Report"
        confirmColor="blue"
      />

      <ConfirmationModal
        isOpen={showDeleteModal}
        onClose={() => {
          setShowDeleteModal(false)
          setExpenseToDelete(null)
        }}
        onConfirm={handleDelete}
        title="Delete Expense"
        message="Are you sure you want to delete this expense? This action cannot be undone."
        confirmText="Delete Expense"
        confirmColor="red"
      />

      <EditExpenseModal
        isOpen={showEditModal}
        onClose={() => {
          setShowEditModal(false)
          setSelectedExpense(null)
        }}
        onSave={handleSaveEdit}
        expense={selectedExpense}
      />
    </>
  )
}

export default ExpenseList